feat: Improve pyproject.toml and remove setup.py
Currently, non-editable install have an issue:

```bash
pip install "hip-attention@git+https://github.com/DeepAuto-AI/hip-attention@7d7df7388f0795adc44307ee32b11880c036ab1b" --no-build-isolation

python

>>> import timber
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/liam/miniconda3/envs/compression/lib/python3.11/site-packages/timber/__init__.py", line 1, in <module>
    from timber.models.timber_attention.attention1_block_gpu import (
ModuleNotFoundError: No module named 'timber.models'
```

This is because the following `setup.py` installs only files in `timber`
folder, not recursively installs subfolders. So it only installs
`__init__.py` in `timber` folder in non-editable install:

```
 package_dir={"timber": "timber"},
```

See: https://docs.python.org/3.11/distutils/setupscript.html

To resolve issue and to make our modules more standardized, we can
implement our setup.py features in pyproject.toml, and remove the
current setup.py.

You can also wee our Python module guide.

https://www.notion.so/deepauto/Python-Module-Guide-abee9aba677f40da8f5be3bb28b5e521?pvs=4